site_name: Acceso a datos
site_url: https://bpaterna.github.io/acceso_datos/
site_author: Begoña Paterna
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: red
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
nav:
  - Presentación: index.md
  - Contenido:
    - 1. Acceso a ficheros: 1_Ficheros.md
    - 2. Acceso a BD relacionales: 2_BD_relacionales.md
  - Material adicional:
    - DB Browser: db_browser_sqlite.md
    - DBeaver: dbeaver.md
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
plugins:
  - with-pdf:
      output_path: pdf/acceso_datos.pdf
      cover: true
      toc_title: "Índice"
